#!/usr/bin/env python3
import os
import json
import re
from datetime import datetime, time
from decimal import Decimal

import psycopg2
from psycopg2.extras import execute_batch

# DB config from env (same names as docker-compose for convenience)
DB_HOST = os.getenv("POSTGRES_HOST", "localhost")
DB_PORT = int(os.getenv("POSTGRES_PORT", "5432"))
DB_USER = os.getenv("POSTGRES_USER", "fooduser")
DB_PASSWORD = os.getenv("POSTGRES_PASSWORD", "foodpass")
DB_NAME = os.getenv("POSTGRES_DB", "fooddb")

# JSON file locations (you can override with env if needed)
RESTAURANTS_JSON = os.getenv("RESTAURANTS_JSON", "restaurant_with_menu.json")
USERS_JSON = os.getenv("USERS_JSON", "users_with_purchase_history.json")


def load_json(path: str):
    print(f"Loading JSON from {path} ...")
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def connect_db():
    print(f"Connecting to Postgres at {DB_HOST}:{DB_PORT} db={DB_NAME} ...")
    conn = psycopg2.connect(
        host=DB_HOST,
        port=DB_PORT,
        user=DB_USER,
        password=DB_PASSWORD,
        dbname=DB_NAME,
    )
    conn.autocommit = False
    return conn


def insert_restaurants_and_menu(conn, restaurants_data):
    """
    Insert into restaurants and menu_items.
    Returns:
        restaurant_name_to_id: dict[str, int]
        menu_key_to_id: dict[(str, str), int] mapping (restaurantName, dishName) -> menu_item.id
    """
    cur = conn.cursor()

    restaurant_name_to_id = {}
    menu_key_to_id = {}
    restaurant_failures = []
    menu_item_failures = []

    for r in restaurants_data:
        name = r.get("restaurantName", "").strip()
        if not name:
            restaurant_failures.append(("Missing restaurantName", str(r)[:100]))
            continue

        try:
            cash_balance = Decimal(str(r.get("cashBalance", 0)))
        except (ValueError, TypeError) as e:
            restaurant_failures.append((f"Invalid cashBalance for '{name}': {e}", str(r)[:100]))
            continue

        # Insert restaurant (id is generated by SERIAL)
        try:
            cur.execute(
                """
                INSERT INTO restaurants (name, cash_balance, timezone)
                VALUES (%s, %s, %s)
                ON CONFLICT (name) DO UPDATE
                SET cash_balance = EXCLUDED.cash_balance
                RETURNING id
                """,
                (name, cash_balance, "Asia/Dhaka"),
            )
            restaurant_id = cur.fetchone()[0]
            restaurant_name_to_id[name] = restaurant_id
        except Exception as e:
            restaurant_failures.append((f"Failed to insert restaurant '{name}': {e}", str(r)[:100]))
            continue

        # Insert menu items
        for item in r.get("menu", []):
            dish_name = item.get("dishName", "").strip()
            # Handle blank dishName: set to "[Unnamed]" and is_active=False
            if not dish_name:
                dish_name = "[Unnamed]"
                is_active = False
            else:
                is_active = True

            try:
                price = Decimal(str(item.get("price", 0)))
            except (ValueError, TypeError) as e:
                menu_item_failures.append((f"Invalid price for dish '{dish_name}' in '{name}': {e}", str(item)[:100]))
                continue

            try:
                cur.execute(
                    """
                    INSERT INTO menu_items (restaurant_id, name, price, is_active)
                    VALUES (%s, %s, %s, %s)
                    RETURNING id
                    """,
                    (restaurant_id, dish_name, price, is_active),
                )
                menu_item_id = cur.fetchone()[0]
                menu_key_to_id[(name, dish_name)] = menu_item_id
            except Exception as e:
                menu_item_failures.append((f"Failed to insert menu item '{dish_name}' for '{name}': {e}", str(item)[:100]))
                continue

    cur.close()
    conn.commit()
    
    print(f"Inserted/updated {len(restaurant_name_to_id)} restaurants and "
          f"{len(menu_key_to_id)} menu items.")
    
    if restaurant_failures:
        print(f"\n⚠️  RESTAURANT FAILURES ({len(restaurant_failures)}):")
        for error, data in restaurant_failures[:10]:  # Show first 10
            print(f"  - {error}")
        if len(restaurant_failures) > 10:
            print(f"  ... and {len(restaurant_failures) - 10} more")
    
    if menu_item_failures:
        print(f"\n⚠️  MENU ITEM FAILURES ({len(menu_item_failures)}):")
        for error, data in menu_item_failures[:10]:  # Show first 10
            print(f"  - {error}")
        if len(menu_item_failures) > 10:
            print(f"  ... and {len(menu_item_failures) - 10} more")
    
    return restaurant_name_to_id, menu_key_to_id


def insert_users(conn, users_data):
    cur = conn.cursor()

    rows = []
    failures = []
    
    for u in users_data:
        try:
            user_id = int(u["id"])
            name = u.get("name", "").strip()
            if not name:
                failures.append((f"Missing name for user id {u.get('id')}", str(u)[:100]))
                continue
            
            try:
                cash_balance = Decimal(str(u.get("cashBalance", 0)))
            except (ValueError, TypeError) as e:
                failures.append((f"Invalid cashBalance for user {user_id}: {e}", str(u)[:100]))
                continue
            
            rows.append((user_id, name, cash_balance))
        except (KeyError, ValueError, TypeError) as e:
            failures.append((f"Invalid user data: {e}", str(u)[:100]))
            continue

    if rows:
        try:
            execute_batch(
                cur,
                """
                INSERT INTO users (id, name, cash_balance)
                VALUES (%s, %s, %s)
                ON CONFLICT (id) DO UPDATE
                SET name = EXCLUDED.name,
                    cash_balance = EXCLUDED.cash_balance
                """,
                rows,
                page_size=100,
            )
        except Exception as e:
            print(f"ERROR: Batch insert of users failed: {e}")
            failures.append((f"Batch insert error: {e}", f"{len(rows)} users"))

    cur.close()
    conn.commit()
    print(f"Inserted/updated {len(rows)} users.")
    
    if failures:
        print(f"\n⚠️  USER FAILURES ({len(failures)}):")
        for error, data in failures[:10]:
            print(f"  - {error}")
        if len(failures) > 10:
            print(f"  ... and {len(failures) - 10} more")


def parse_opening_hours(opening_hours_str: str):
    """
    Parse opening hours string into list of (day_of_week, open_time, close_time) tuples.
    Overnight hours are split into two rows: one ending at 23:59:59 on current day,
    and one starting at 00:00:00 on the next day.
    
    Format: "Mon, Fri 2:30 pm - 8 pm / Tues 11 am - 2 pm / Weds 1:15 pm - 3:15 am / ..."
    
    Returns:
        list of tuples: [(day_of_week, open_time, close_time), ...]
        day_of_week: int (0=Sunday, 1=Monday, ..., 6=Saturday)
        open_time, close_time: time objects
    """
    if not opening_hours_str or not opening_hours_str.strip():
        return []
    
    # Day name mapping
    day_map = {
        "sun": 0, "sunday": 0,
        "mon": 1, "monday": 1,
        "tues": 2, "tuesday": 2,
        "wed": 3, "weds": 3, "wednesday": 3,
        "thurs": 4, "thu": 4, "thursday": 4,
        "fri": 5, "friday": 5,
        "sat": 6, "saturday": 6,
    }
    
    results = []
    
    # Split by "/" to get day-time pairs
    parts = [p.strip() for p in opening_hours_str.split("/")]
    
    for part in parts:
        if not part:
            continue
        
        # Extract time range: "2:30 pm - 8 pm" or "1:15 pm - 3:15 am" or "11 am - 2 pm"
        # Handle both formats: with minutes "2:30 pm" and without "8 pm"
        time_match = re.search(
            r'(\d{1,2})(?::(\d{2}))?\s*(am|pm)\s*-\s*(\d{1,2})(?::(\d{2}))?\s*(am|pm)',
            part,
            re.IGNORECASE
        )
        if not time_match:
            print(f"WARNING: Could not parse time range in '{part}', skipping")
            continue
        
        # Parse times (minutes are optional, default to 0)
        open_hour = int(time_match.group(1))
        open_min = int(time_match.group(2)) if time_match.group(2) else 0
        open_ampm = time_match.group(3).lower()
        close_hour = int(time_match.group(4))
        close_min = int(time_match.group(5)) if time_match.group(5) else 0
        close_ampm = time_match.group(6).lower()
        
        # Convert to 24-hour format
        if open_ampm == "pm" and open_hour != 12:
            open_hour += 12
        elif open_ampm == "am" and open_hour == 12:
            open_hour = 0
        
        if close_ampm == "pm" and close_hour != 12:
            close_hour += 12
        elif close_ampm == "am" and close_hour == 12:
            close_hour = 0
        
        open_time = time(open_hour, open_min)
        close_time = time(close_hour, close_min)
        
        # Determine if overnight (close_time < open_time means it spans to next day)
        is_overnight = close_time < open_time
        
        # Extract day names (before the time range)
        day_part = part[:time_match.start()].strip()
        
        # Parse day ranges and individual days
        # Handle patterns like: "Mon - Weds", "Weds - Thurs", "Mon, Fri", "Mon - Weds, Fri"
        day_numbers = []
        
        # First, split by comma to handle multiple day groups
        day_groups = [d.strip().lower() for d in re.split(r'[,&]', day_part) if d.strip()]
        
        for day_group in day_groups:
            # Check if it's a range (contains " - " or "-")
            range_match = re.search(r'(\w+)\s*-\s*(\w+)', day_group)
            if range_match:
                # It's a day range like "mon - weds"
                start_day_name = range_match.group(1).strip()
                end_day_name = range_match.group(2).strip()
                
                start_day = day_map.get(start_day_name)
                end_day = day_map.get(end_day_name)
                
                if start_day is None or end_day is None:
                    print(f"WARNING: Unknown day name in range '{day_group}' in '{part}', skipping")
                    continue
                
                # Expand the range to include all days
                # Handle wrap-around (e.g., Sat - Mon)
                if start_day <= end_day:
                    # Normal range: Mon(1) to Weds(3) -> [1, 2, 3]
                    day_numbers.extend(range(start_day, end_day + 1))
                else:
                    # Wrap-around: Sat(6) to Mon(1) -> [6, 0, 1]
                    day_numbers.extend(range(start_day, 7))  # 6
                    day_numbers.extend(range(0, end_day + 1))  # 0, 1
            else:
                # Single day
                day_num = day_map.get(day_group)
                if day_num is None:
                    print(f"WARNING: Unknown day name '{day_group}' in '{part}', skipping")
                    continue
                day_numbers.append(day_num)
        
        # Remove duplicates
        day_numbers = list(set(day_numbers))
        
        # Sort, but handle wrap-around correctly
        # If we have both high (5,6) and low (0,1) numbers, it might be a wrap-around
        if day_numbers and max(day_numbers) - min(day_numbers) > 3:
            # Likely a wrap-around, keep original order or sort within each segment
            # For now, just sort normally - the overnight logic will handle it
            day_numbers = sorted(day_numbers)
        else:
            # Normal range, sort
            day_numbers = sorted(day_numbers)
        
        # For each day in the range, add the time slots
        for idx, day_of_week in enumerate(day_numbers):
            if is_overnight:
                # For overnight hours in a range:
                # - First day: open_time to 23:59:59
                # - Last day: 00:00:00 to close_time
                # - Middle days: 00:00:00 to 23:59:59 (full day)
                end_of_day = time(23, 59, 59)
                start_of_day = time(0, 0, 0)
                
                if idx == 0:
                    # First day: open_time to 23:59:59
                    results.append((day_of_week, open_time, end_of_day))
                elif idx == len(day_numbers) - 1:
                    # Last day: 00:00:00 to close_time
                    results.append((day_of_week, start_of_day, close_time))
                else:
                    # Middle days: full day (00:00:00 to 23:59:59)
                    results.append((day_of_week, start_of_day, end_of_day))
            else:
                # Normal hours: same time for all days in range
                results.append((day_of_week, open_time, close_time))
    
    return results


def insert_opening_hours(conn, restaurants_data, restaurant_name_to_id):
    """
    Parse and insert opening hours for all restaurants.
    Handles multiple time ranges per day by inserting multiple rows.
    """
    cur = conn.cursor()
    
    rows_to_insert = []
    total_hours = 0
    failures = []
    skipped_restaurants = []
    
    for r in restaurants_data:
        restaurant_name = r.get("restaurantName", "").strip()
        if not restaurant_name:
            failures.append(("Missing restaurantName", str(r)[:100]))
            continue
        
        restaurant_id = restaurant_name_to_id.get(restaurant_name)
        
        if restaurant_id is None:
            skipped_restaurants.append(restaurant_name)
            continue
        
        opening_hours_str = r.get("openingHours", "")
        if not opening_hours_str:
            continue
        
        # Parse opening hours
        try:
            parsed_hours = parse_opening_hours(opening_hours_str)
        except Exception as e:
            failures.append((f"Failed to parse opening hours for '{restaurant_name}': {e}", opening_hours_str[:100]))
            continue
        
        # Add to batch insert list
        for day_of_week, open_time, close_time in parsed_hours:
            rows_to_insert.append((restaurant_id, day_of_week, open_time, close_time))
            total_hours += 1
    
    # Batch insert
    if rows_to_insert:
        try:
            execute_batch(
                cur,
                """
                INSERT INTO restaurant_opening_hours
                    (restaurant_id, day_of_week, open_time, close_time)
                VALUES (%s, %s, %s, %s)
                """,
                rows_to_insert,
                page_size=100,
            )
        except Exception as e:
            print(f"ERROR: Batch insert of opening hours failed: {e}")
            failures.append((f"Batch insert error: {e}", f"{len(rows_to_insert)} records"))
    
    cur.close()
    conn.commit()
    
    restaurants_with_hours = len(set(r[0] for r in rows_to_insert)) if rows_to_insert else 0
    print(f"Inserted {total_hours} opening hour records for {restaurants_with_hours} restaurants.")
    
    if skipped_restaurants:
        print(f"\n⚠️  SKIPPED OPENING HOURS ({len(skipped_restaurants)} restaurants not found):")
        for name in skipped_restaurants[:10]:
            print(f"  - {name}")
        if len(skipped_restaurants) > 10:
            print(f"  ... and {len(skipped_restaurants) - 10} more")
    
    if failures:
        print(f"\n⚠️  OPENING HOURS FAILURES ({len(failures)}):")
        for error, data in failures[:10]:
            print(f"  - {error}")
        if len(failures) > 10:
            print(f"  ... and {len(failures) - 10} more")


def parse_transaction_datetime(dt_str: str):
    # Example in JSON: "02/10/2020 04:09 AM"
    if not dt_str:
        return None
    try:
        return datetime.strptime(dt_str, "%m/%d/%Y %I:%M %p")
    except ValueError:
        print(f"WARNING: could not parse transactionDate '{dt_str}', using now()")
        return None


def insert_orders_from_purchase_history(conn, users_data,
                                        restaurant_name_to_id, menu_key_to_id):
    cur = conn.cursor()
    orders_count = 0
    items_count = 0
    order_failures = []
    item_failures = []
    skipped_purchases = []

    for u in users_data:
        try:
            user_id = int(u["id"])
        except (KeyError, ValueError, TypeError) as e:
            order_failures.append((f"Invalid user id: {e}", str(u)[:100]))
            continue
        
        for ph in u.get("purchaseHistory", []):
            restaurant_name = ph.get("restaurantName", "").strip()
            dish_name = ph.get("dishName", "").strip()
            
            if not restaurant_name:
                skipped_purchases.append((f"User id: {user_id} - Missing restaurantName", str(ph)[:100]))
                continue
            
            # Handle missing dishName: set to "[Unnamed]" instead of skipping
            if not dish_name:
                dish_name = "[Unnamed]"

            try:
                total_amount = Decimal(str(ph.get("transactionAmount", 0)))
            except (ValueError, TypeError) as e:
                skipped_purchases.append((f"User id: {user_id} - Invalid transactionAmount for '{restaurant_name}' - '{dish_name}': {e}", str(ph)[:100]))
                continue

            created_at = parse_transaction_datetime(ph.get("transactionDate", ""))

            restaurant_id = restaurant_name_to_id.get(restaurant_name)
            if restaurant_id is None:
                skipped_purchases.append((f"User id: {user_id} - Restaurant '{restaurant_name}' not found", dish_name))
                continue

            # Might be missing if dish in history doesn't exist in menu anymore
            # For "[Unnamed]" dishes, menu_item_id will be None if not found
            menu_item_id = menu_key_to_id.get((restaurant_name, dish_name))

            quantity = 1
            unit_price = total_amount
            line_amount = total_amount

            # Insert order
            try:
                cur.execute(
                    """
                    INSERT INTO orders (user_id, restaurant_id, total_amount, created_at)
                    VALUES (%s, %s, %s, COALESCE(%s, now()))
                    RETURNING id
                    """,
                    (user_id, restaurant_id, total_amount, created_at),
                )
                order_id = cur.fetchone()[0]
                orders_count += 1
            except Exception as e:
                order_failures.append((f"Failed to insert order for user {user_id}, restaurant '{restaurant_name}': {e}", str(ph)[:100]))
                continue

            # Insert order item
            try:
                cur.execute(
                    """
                    INSERT INTO order_items
                        (order_id, menu_item_id, dish_name, unit_price, quantity, line_amount)
                    VALUES (%s, %s, %s, %s, %s, %s)
                    """,
                    (order_id, menu_item_id, dish_name, unit_price, quantity, line_amount),
                )
                items_count += 1
            except Exception as e:
                item_failures.append((f"Failed to insert order item for order {order_id}, dish '{dish_name}': {e}", str(ph)[:100]))
                continue

    cur.close()
    conn.commit()
    print(f"Inserted {orders_count} orders and {items_count} order_items.")
    
    if skipped_purchases:
        print(f"\n⚠️  SKIPPED PURCHASES ({len(skipped_purchases)}):")
        for error, data in skipped_purchases[:10]:
            print(f"  - {error}")
        if len(skipped_purchases) > 10:
            print(f"  ... and {len(skipped_purchases) - 10} more")
    
    if order_failures:
        print(f"\n⚠️  ORDER FAILURES ({len(order_failures)}):")
        for error, data in order_failures[:10]:
            print(f"  - {error}")
        if len(order_failures) > 10:
            print(f"  ... and {len(order_failures) - 10} more")
    
    if item_failures:
        print(f"\n⚠️  ORDER ITEM FAILURES ({len(item_failures)}):")
        for error, data in item_failures[:10]:
            print(f"  - {error}")
        if len(item_failures) > 10:
            print(f"  ... and {len(item_failures) - 10} more")


def main():
    restaurants_data = load_json(RESTAURANTS_JSON)
    users_data = load_json(USERS_JSON)

    conn = connect_db()
    try:
        restaurant_name_to_id, menu_key_to_id = insert_restaurants_and_menu(conn, restaurants_data)
        insert_opening_hours(conn, restaurants_data, restaurant_name_to_id)
        insert_users(conn, users_data)
        insert_orders_from_purchase_history(conn, users_data,
                                            restaurant_name_to_id, menu_key_to_id)
    except Exception as e:
        print(f"\n❌ FATAL ERROR: ETL process failed: {e}")
        import traceback
        traceback.print_exc()
        raise
    finally:
        conn.close()
        print("\n✅ ETL process completed.")


if __name__ == "__main__":
    main()
